"""Small psycopg connection adapter for the existing database query surface."""

from __future__ import annotations

from contextlib import contextmanager
import re
from typing import Any, Iterator


_POOLS: dict[str, Any] = {}


def _translate_sql(sql: str) -> str:
    translated = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", sql, flags=re.I)
    ignored = translated != sql
    translated = translated.replace("?", "%s")
    if ignored and "ON CONFLICT" not in translated.upper():
        stripped = translated.rstrip().rstrip(";")
        translated = stripped + " ON CONFLICT DO NOTHING"
    return translated


class PostgresConnectionAdapter:
    """Expose the execute API used by db.py while retaining dict-like rows."""

    def __init__(self, connection: Any):
        self.connection = connection

    def execute(self, sql: str, params: tuple | list = ()):
        return self.connection.execute(_translate_sql(sql), params)

    def executescript(self, _script: str):
        raise NotImplementedError("PostgreSQL schema uses initialize_postgres_schema")


def _pool(database_url: str):
    pool = _POOLS.get(database_url)
    if pool is None:
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool

        pool = ConnectionPool(
            conninfo=database_url,
            min_size=0,
            max_size=4,
            kwargs={"row_factory": dict_row},
            open=True,
        )
        _POOLS[database_url] = pool
    return pool


@contextmanager
def postgres_connection(database_url: str) -> Iterator[PostgresConnectionAdapter]:
    """Borrow one bounded pooled connection and commit/rollback with context exit."""
    with _pool(database_url).connection() as connection:
        yield PostgresConnectionAdapter(connection)


def initialize_postgres_schema(database_url: str) -> None:
    """Create production tables and dashboard indexes idempotently."""
    with postgres_connection(database_url) as connection:
        for statement in POSTGRES_SCHEMA.split(";"):
            if statement.strip():
                connection.execute(statement)


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id TEXT NOT NULL, source_platform TEXT NOT NULL, url TEXT NOT NULL UNIQUE,
 title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL,
 image_url TEXT NOT NULL, raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
 filter_score INTEGER NOT NULL DEFAULT 0, filter_status TEXT NOT NULL DEFAULT '',
 filter_reason TEXT NOT NULL DEFAULT '', opportunity_type TEXT NOT NULL DEFAULT 'uncertain',
 feasibility_status TEXT NOT NULL DEFAULT 'REVIEW', feasibility_score INTEGER NOT NULL DEFAULT 0,
 feasibility_reason TEXT NOT NULL DEFAULT '', risk_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
 positive_signals JSONB NOT NULL DEFAULT '[]'::jsonb, record_role TEXT NOT NULL DEFAULT 'uncertain',
 demand_signal_status TEXT NOT NULL DEFAULT '', demand_signal_score INTEGER NOT NULL DEFAULT 0,
 demand_signal_type TEXT NOT NULL DEFAULT '', demand_signal_reason TEXT NOT NULL DEFAULT '',
 demand_opportunity_status TEXT NOT NULL DEFAULT '', demand_opportunity_score INTEGER NOT NULL DEFAULT 0,
 demand_opportunity_reason TEXT NOT NULL DEFAULT '', opportunity_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
 commodity_status TEXT NOT NULL DEFAULT '', commodity_score INTEGER NOT NULL DEFAULT 0,
 commodity_reason TEXT NOT NULL DEFAULT '', commodity_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, first_seen_at TIMESTAMPTZ,
 last_seen_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS processed_projects (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, url TEXT NOT NULL UNIQUE,
 source_platform TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '',
 pushed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS micro_innovation_candidates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id TEXT NOT NULL UNIQUE,
 candidate_type TEXT NOT NULL, source_platform TEXT NOT NULL, source_url TEXT NOT NULL UNIQUE,
 title TEXT NOT NULL, summary TEXT NOT NULL, candidate_score INTEGER NOT NULL,
 feasibility_score INTEGER NOT NULL, demand_score INTEGER NOT NULL,
 market_validation_score INTEGER NOT NULL, micro_innovation_score INTEGER NOT NULL,
 reason TEXT NOT NULL, signals JSONB NOT NULL DEFAULT '[]'::jsonb,
 raw_reference_id TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS ai_triage_results (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id TEXT NOT NULL,
 triage_status TEXT NOT NULL, triage_score INTEGER NOT NULL, confidence TEXT NOT NULL,
 primary_reason TEXT NOT NULL, opportunity_type TEXT NOT NULL, key_opportunity TEXT NOT NULL,
 main_risks JSONB NOT NULL DEFAULT '[]'::jsonb, needs_deep_analysis BOOLEAN NOT NULL,
 provider TEXT NOT NULL, model TEXT NOT NULL, display_title_zh TEXT,
 primary_reason_zh TEXT, key_opportunity_zh TEXT, main_risks_zh JSONB NOT NULL DEFAULT '[]'::jsonb,
 analyzed_at TIMESTAMPTZ NOT NULL, UNIQUE(candidate_id, provider, model)
);
CREATE TABLE IF NOT EXISTS deep_analysis_results (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id TEXT NOT NULL,
 provider TEXT NOT NULL, model TEXT NOT NULL, analysis_version TEXT NOT NULL,
 deep_score INTEGER NOT NULL, recommended_next_step TEXT NOT NULL, result_json JSONB NOT NULL,
 input_characters INTEGER NOT NULL, input_tokens INTEGER, output_tokens INTEGER, total_tokens INTEGER,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 UNIQUE(candidate_id, provider, model, analysis_version)
);
CREATE TABLE IF NOT EXISTS software_analysis_results (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id TEXT NOT NULL,
 provider TEXT NOT NULL, model TEXT NOT NULL, analysis_version TEXT NOT NULL,
 software_score INTEGER NOT NULL, recommended_next_step TEXT NOT NULL, result_json JSONB NOT NULL,
 input_characters INTEGER NOT NULL, input_tokens INTEGER, output_tokens INTEGER, total_tokens INTEGER,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 UNIQUE(candidate_id, provider, model, analysis_version)
);
CREATE TABLE IF NOT EXISTS product_metric_snapshots (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id BIGINT NOT NULL REFERENCES products(id), source_platform TEXT NOT NULL,
 captured_at TIMESTAMPTZ NOT NULL, metric_type TEXT NOT NULL, metric_data JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS pipeline_runs (
 run_id TEXT PRIMARY KEY, started_at TIMESTAMPTZ NOT NULL, finished_at TIMESTAMPTZ,
 status TEXT NOT NULL, error TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS pipeline_source_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id TEXT NOT NULL REFERENCES pipeline_runs(run_id),
 source_platform TEXT NOT NULL, fetched INTEGER NOT NULL DEFAULT 0, new_count INTEGER NOT NULL DEFAULT 0,
 updated_count INTEGER NOT NULL DEFAULT 0, failed BOOLEAN NOT NULL DEFAULT FALSE,
 rejected INTEGER NOT NULL DEFAULT 0, candidates_created INTEGER NOT NULL DEFAULT 0,
 error TEXT NOT NULL DEFAULT '', UNIQUE(run_id, source_platform)
);
CREATE TABLE IF NOT EXISTS specificity_results (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_id TEXT NOT NULL,
 specificity_status TEXT NOT NULL, specificity_score INTEGER NOT NULL,
 specificity_reason TEXT NOT NULL, specificity_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
 rule_version TEXT NOT NULL, evaluated_at TIMESTAMPTZ NOT NULL,
 UNIQUE(candidate_id, rule_version)
);
CREATE TABLE IF NOT EXISTS user_product_feedback (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type TEXT NOT NULL,
 entity_id TEXT NOT NULL, feedback_type TEXT NOT NULL, note TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 UNIQUE(entity_type, entity_id)
);
CREATE TABLE IF NOT EXISTS re_evaluation_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type TEXT NOT NULL,
 entity_id TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'PENDING',
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_source ON products(source_platform);
CREATE INDEX IF NOT EXISTS idx_products_first_seen ON products(first_seen_at);
CREATE INDEX IF NOT EXISTS idx_products_last_seen ON products(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_products_filter_status ON products(filter_status);
CREATE INDEX IF NOT EXISTS idx_products_feasibility_status ON products(feasibility_status);
CREATE INDEX IF NOT EXISTS idx_products_commodity_status ON products(commodity_status);
CREATE INDEX IF NOT EXISTS idx_triage_candidate_provider_model ON ai_triage_results(candidate_id, provider, model);
CREATE INDEX IF NOT EXISTS idx_feedback_entity ON user_product_feedback(entity_type, entity_id);
"""
